all: fire ipers plane polygone pulsar simple triangle

fire:
	cd fire/; make

ipers:
	cd ipers/; make

plane:	
	cd plane/; make

polygone:
	cd polygone/; make

pulsar:
	cd pulsar/; make

simple:
	cd simple/; make

triangle:
	cd triangle/; make

clean:
	rm */test
